### ISSUE TITLE
Функция test_key не проверяет ключи.

### ISSUE THREAD

**Issue by zenoize** [Kingston-kms/eset_mirror_script#1]
Класс mirror class, функция Tools::download_file, опция CURLOPT_USERPWD бесполезна. Если убрать CURLOPT_USERPWD и использовать CURLOPT_NOBODY,  сервер все равно возвращает http_code 200 и download_content_length больше 0. 
Проверять с помощью  CURLOPT_USERPWD можно только если убрать CURLOPT_NOBODY

**Comment by Kingston-kms** [comment]
CURLOPT_USERPWD необходима для авторизации на зеркалах, где это требуется (версии выше 9ой).
CURLOPT_NOBODY отвечает за получение содержимого файла.
