### ISSUE TITLE
Расположение директорий

### ISSUE THREAD

**Issue by Neur0z** [Kingston-kms/eset_mirror_script#2]
Доброго дня!
Для чего дублируются файлы из директорий вида "v3-rel-sta" в "eset_upd\v13" ?
Это как временная папка? Просто в таком случае увеличивается занятое пространство вдвое.
Скрипт просто замечательный!

**Comment by Kingston-kms** [comment]
Исправил создание символьных ссылок. Проверьте, рекомендую папку www полностью очистить перед запуском
